spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
#    username:
#    password:
#    url:jdbc:mysql://localhost:3306/person_example
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework: info